### ISSUE TITLE
为什么您的readme中说支持forwardAddress和led显示，实际使用却并没有任何用处呢

### ISSUE THREAD

**Issue by YinHangCoding** [YinHangCode/homebridge-phicomm-air_detector#1]
如题，您在Readme中说：
listenPort是监听端口，如果让M1直接发包过来写9000。
forwardAddress是转发地址，可以转发给斐讯服务器或者其它需要用数据的地方。
但是设置后并不能正常转发，使用repository内搜索forwardAddress也没有搜索到相关的东西
https://github.com/YinHangCode/homebridge-phicomm-air_detector/search?utf8=✓&q=forwardAddress&type=
这个是不是太难了您写不出来啊？

**Comment by cxlwill** [comment]
所以你无聊到注册一个高仿账号，到别人的 Github 里冷嘲热讽？直接用主号啊 @Zzm317。然后大方地放出你的同项目地址啊： https://github.com/Zzm317/homebridge-phicomm-m1。用户自由选择嘛~ Maybe Mr.Yin 真的是写不出来呢，没有你厉害呢，你最棒了呢，别人代码全部抄你的呢~~ 然而人家在外打拼，养家糊口，不像你，赋闲在家没事干，住着郊区大房子，跑人家项目里怼人玩~ 你最棒棒了~ ：）

**Comment by YinHangCoding** [comment]
这github叫yinhang的可不少啊
你看看叫yinhang的项目 https://github.com/search?utf8=%E2%9C%93&q=yinhang&type=
再看看叫yinhang的用户 https://github.com/search?q=yinhang&type=Users&utf8=%E2%9C%93
怎么到我这就成高仿号了？
空口无凭可不好啊
有这时间打情骂俏 不如好好写写你的document 说不定写好了人家就爱上你了和你共度余生呢？
顺便看了下那个项目 确实写完了啊 你别打不过就来黑啊
慢走不送

**Comment by cxlwill** [comment]
玩笑了~~ 就当你承认你是那位了吧~~ 是你自己跑来黑，我作为你眼中的『打情骂俏』对象过来防御一下啊~ 真不好意思，你才是这里的客人，你慢走不送。哦不，别慢走了，赶紧圆润地离开吧~~ ：）

**Comment by YinHangCoding** [comment]
我是哪位？您来告诉我一下呗 本人不才 只知道像您这样头像的一般都是dalao 毕竟这角色可是连自己是不是普通的人类都怀疑的啊

**Comment by cxlwill** [comment]
另外孩子，有些话能说，有些不能说。人家家庭幸福美满，你在人家的群里不合群被请走了，过来兴风作浪，胡言乱语，真的是滑天下之大稽。不如反思一下，为什么别人都可以和和气气技术合作交流讨论，你要被请走呢？~~ 你就和你的『未婚夫』幸福地在上海郊区的大房子里终老吧~ 劝你找个正经工作，指不定哪天人家看不上双证没拿休学的你，房子都没了~~

**Comment by cxlwill** [comment]
你是谁我并不关心，承不承认和我半毛钱关系没有，也不靠你收钱吃饭。说错了，您就当一乐，说中了，您早已心知肚明~~~ 祝你健康成长每一天。

**Comment by YinHangCoding** [comment]
是啊 我也不需要靠和你聊天来找乐子 大家彼此彼此 何必呢 
不如您催促一下您那位 在外打拼，养家糊口 的Mr.Yin来写一下他的项目？
